spring.application.name=task-manager
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.web.error.include-stacktrace=never
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:5MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:51MB}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR
logging.level.org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver=ERROR
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION:us-east-1}
cloud.aws.s3.bucket=${AWS_BUCKET_NAME}
app.max-image-per-task=${MAX_IMAGE_PER_TASK:5}
